# Generated by Django 5.1.1 on 2024-12-02 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_customuser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tasks.group'),
        ),
    ]
